### ISSUE TITLE
Laravel 9 in the future ? 8.83.7 actually

### ISSUE THREAD

**Issue by tranKILL** [1CAMOU/laravelte#1]
inertiajs/inertia-laravel 0.5.4 ? 0.4.4 actually

And all the rest if you can, I didn't try, now time for now, sorry

Thanks for your work, seems nice :)

**Comment by michaelsieminski** [comment]
@tranKILL Updated the package to latest Laravel, Inertia, Tailwind & Svelte :)

**Comment by tranKILL** [comment]
Oh yeah, big TY :)
Will try that tomorrow
