### ISSUE TITLE
Could you do a Laravelte with Jetstream?

### ISSUE THREAD

**Issue by algonorth** [1CAMOU/laravelte#2]
I'd like to convert to Svelte but Laravel Jetstream is setup with Vue. Could you do a version of Jetstream done with Svelte instead of Vue?

**Comment by michaelsieminski** [comment]
Hi @bit-pax, i was thinking about doing that for a while tbh, I'm probably going to do it sooner or later for sure

**Comment by ramabie** [comment]
this will be a spectacular masterpiece

**Comment by michaelsieminski** [comment]
https://github.com/1CAMOU/breeze-svelte made a breeze version of this,
jetstream is coming next
